#base image
FROM ubuntu:22.04
MAINTAINER lancelot_zhu@163.com

#set environmental variables
ENV TZ="Asia/Shanghai"

#use local apt sources
COPY sources.list /etc/apt/sources.list

#install server software baseline
RUN apt update \
    && apt -y install tzdata \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && useradd -r -m -s /bin/bash admin \
    && echo "admin:admin" | chpasswd \
    && apt -y install sudo \
    && echo "%admin ALL=(ALL) ALL" > /etc/sudoers.d/admin \
    && apt -y install nano \
    && apt -y install curl \
    && apt -y install net-tools \
    && apt -y install iputils-ping \
    && apt -y install openjdk-8-jre-headless \
    && apt -y install supervisor \
    && rm -rf /var/lib/apt/lists/*

#configure supervisor
COPY supervisord.conf /etc/supervisor/supervisord.conf

#expose port
EXPOSE 9001

#startup supervisor
ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
