#base image
FROM openjdk:8-jre-slim-bullseye
MAINTAINER lancelot_zhu@163.com

#set environmental variables
ENV TZ="Asia/Shanghai"

# change apt source
RUN sed -i "s@http://\(deb\|security\).debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list

#install server software baseline
RUN apt update \
    && apt -y upgrade \
    && apt -y install tzdata \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && useradd -r -m -s /bin/bash admin \
    && apt -y install curl \
    && apt -y install procps \
    && apt -y install dumb-init \
    && rm -rf /var/lib/apt/lists/*

#set work dir and user
WORKDIR /home/admin
USER admin

#startup java program
ENTRYPOINT ["dumb-init", ""java", "-version"]
