server:
  port: ${APP_PORT}

spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml
  path: ${LOG_DIR}
  defaultLevel: INFO

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  path: logs
  defaultLevel: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
logging:
  path: logs
  defaultLevel: DEBUG

---
spring:
  config:
    activate:
      on-profile: pre
logging:
  path: logs
  defaultLevel: INFO

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  path: logs
  defaultLevel: WARN