server:
  port: 8000

spring:
  profiles:
    active: dev

logging:
  defaultLevel: INFO
  config: classpath:logback-spring.xml

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  path: logs
  defaultLevel: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
logging:
  path: logs
  defaultLevel: DEBUG

---
spring:
  config:
    activate:
      on-profile: pre
logging:
  path: logs
  defaultLevel: INFO

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  path: logs
  defaultLevel: WARN